const OMAH_SABUN_CONFIG={whatsappNumber:'6282323340408',sheetCsvUrl:'',businessName:'Omah Sabun'};
const fallbackProducts=[{nama:'Sabun Cuci Piring',kategori:'Rumah Tangga',harga:'Hubungi admin',ukuran:'Berbagai ukuran',deskripsi:'Untuk kebutuhan rumah, warung, dan usaha makanan.',status:'Ready'},{nama:'Pembersih Lantai',kategori:'Kebersihan Rumah',harga:'Hubungi admin',ukuran:'Berbagai ukuran',deskripsi:'Cocok untuk rumah, kantor, kos, toko, dan laundry.',status:'Ready'},{nama:'Karbol Aromatic',kategori:'Disinfektan',harga:'Hubungi admin',ukuran:'Berbagai ukuran',deskripsi:'Untuk menjaga area tetap bersih dan segar.',status:'Ready'},{nama:'Pewangi Laundry',kategori:'Laundry',harga:'Hubungi admin',ukuran:'Berbagai varian',deskripsi:'Untuk kebutuhan laundry dan pemakaian rumah tangga.',status:'Cek stok'},{nama:'Detergen Cair',kategori:'Laundry',harga:'Hubungi admin',ukuran:'Berbagai ukuran',deskripsi:'Stok rutin untuk kebutuhan cuci harian.',status:'Cek stok'},{nama:'Paket Reseller / Grosir',kategori:'Grosir',harga:'Konsultasi admin',ukuran:'Sesuai kebutuhan',deskripsi:'Untuk toko, reseller, laundry, dan pembelian jumlah banyak.',status:'By request'}];
const state={products:[],filtered:[],selected:new Map()};
const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s),clean=v=>String(v||'').trim();
document.addEventListener('DOMContentLoaded',init);
async function init(){const y=$('#year');if(y)y.textContent=new Date().getFullYear();setupNav();setupReveal();setupWa();await loadCatalog();}
function waUrl(msg){return`https://wa.me/${OMAH_SABUN_CONFIG.whatsappNumber.replace(/\D/g,'')}?text=${encodeURIComponent(msg)}`}
function baseMsg(){return`Halo Admin ${OMAH_SABUN_CONFIG.businessName}, saya ingin bertanya tentang produk kebersihan.\n\nNama:\nAlamat/Kota:\nKebutuhan: Rumah / Reseller / Grosir / Laundry\nProduk yang dicari:\nJumlah kebutuhan:`}
function prodMsg(p,qty=''){return`Halo Admin ${OMAH_SABUN_CONFIG.businessName}, saya ingin order/cek stok produk berikut.\n\nNama:\nAlamat/Kota:\nKebutuhan: Rumah / Reseller / Grosir / Laundry\n\nProduk: ${p.nama}\nKategori: ${p.kategori}\nHarga: ${p.harga}\nUkuran: ${p.ukuran}\nJumlah: ${qty||'Belum diisi'}\n\nMohon info stok, harga final, dan pengirimannya.`}
function cartMsg(){if(!state.selected.size)return baseMsg();let list=[...state.selected.values()].map((p,i)=>`${i+1}. ${p.nama}\n   Kategori: ${p.kategori}\n   Ukuran: ${p.ukuran}\n   Harga: ${p.harga}\n   Jumlah: ${p.qty||'Belum diisi'}`).join('\n');return`Halo Admin ${OMAH_SABUN_CONFIG.businessName}, saya ingin order/cek stok produk berikut.\n\nNama:\nAlamat/Kota:\nKebutuhan: Rumah / Reseller / Grosir / Laundry\n\nDaftar produk:\n${list}\n\nMohon info ketersediaan, harga terbaik, dan cara pengirimannya.`}
function setupWa(){$$('[data-whatsapp-link]').forEach(a=>{a.href=waUrl(baseMsg());a.target='_blank';a.rel='noopener'});$$('[data-whatsapp-cart]').forEach(a=>{a.addEventListener('click',e=>{e.preventDefault();window.open(waUrl(cartMsg()),'_blank','noopener')})})}
function setupNav(){const t=$('[data-nav-toggle]'),m=$('[data-nav-menu]');if(!t||!m)return;t.addEventListener('click',()=>{let o=m.classList.toggle('is-open');t.setAttribute('aria-expanded',String(o))});m.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{m.classList.remove('is-open');t.setAttribute('aria-expanded','false')}))}
function setupReveal(){let items=$$('.reveal');if(!('IntersectionObserver'in window)){items.forEach(i=>i.classList.add('is-visible'));return}let ob=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('is-visible');ob.unobserve(e.target)}}),{threshold:.12});items.forEach(i=>ob.observe(i))}
async function loadCatalog(){setStatus('Memuat katalog...');try{let url=clean(OMAH_SABUN_CONFIG.sheetCsvUrl);if(!url)throw Error('no sheet');let r=await fetch(url,{cache:'no-store'});if(!r.ok)throw Error('sheet error');let rows=parseCSV(await r.text());state.products=norm(rows);if(!state.products.length)throw Error('empty');setStatus(`${state.products.length} produk berhasil dimuat dari Google Sheet.`)}catch(e){state.products=fallbackProducts.map((p,i)=>({...p,id:`produk-${i}`}));setStatus('Katalog contoh tampil. Hubungkan Google Sheet CSV di script.js untuk data asli.')}state.filtered=[...state.products];categories();bindCatalog();renderCatalog()}
function parseCSV(text){let rows=[],row=[],cell='',q=false;for(let i=0;i<text.length;i++){let c=text[i],n=text[i+1];if(c=='"'&&q&&n=='"'){cell+='"';i++}else if(c=='"')q=!q;else if(c==','&&!q){row.push(cell.trim());cell=''}else if((c=='\n'||c=='\r')&&!q){if(cell||row.length){row.push(cell.trim());rows.push(row)}row=[];cell='';if(c=='\r'&&n=='\n')i++}else cell+=c}if(cell||row.length){row.push(cell.trim());rows.push(row)}if(!rows.length)return[];let h=rows.shift().map(key);return rows.map(v=>Object.fromEntries(h.map((x,i)=>[x,v[i]||''])))}
function key(v){return String(v||'').toLowerCase().replace(/[^a-z0-9]+/g,'').trim()}function pick(r,ks){for(let k of ks){let v=r[key(k)];if(v)return v}return''}
function norm(rows){return rows.map((r,i)=>({id:r.id||`produk-${i}`,nama:pick(r,['nama','name','produk','product'])||'Produk Omah Sabun',kategori:pick(r,['kategori','category','jenis'])||'Produk Kebersihan',harga:pick(r,['harga','price','hargagrosir'])||'Hubungi admin',ukuran:pick(r,['ukuran','size','kemasan','volume','satuan'])||'Retail / grosir',deskripsi:pick(r,['deskripsi','description','keterangan','detail'])||'Produk kebersihan untuk kebutuhan rumah dan usaha.',status:pick(r,['status','stok','stock','availability'])||'Cek stok'})).filter(p=>p.nama&&p.nama!='-')}
function categories(){let s=$('#categoryFilter');if(!s)return;let cats=[...new Set(state.products.map(p=>p.kategori).filter(Boolean))].sort();s.innerHTML='<option value="all">Semua kategori</option>'+cats.map(c=>`<option value="${esc(c)}">${esc(c)}</option>`).join('')}
function bindCatalog(){let q=$('#catalogSearch'),c=$('#categoryFilter');q&&q.addEventListener('input',filter);c&&c.addEventListener('change',filter)}
function filter(){let kw=clean($('#catalogSearch')?.value).toLowerCase(),cat=$('#categoryFilter')?.value||'all';state.filtered=state.products.filter(p=>{let text=`${p.nama} ${p.kategori} ${p.deskripsi} ${p.status}`.toLowerCase();return(!kw||text.includes(kw))&&(cat=='all'||p.kategori==cat)});renderCatalog()}
function renderCatalog(){let g=$('#catalogGrid');if(!g)return;if(!state.filtered.length){g.innerHTML='<div class="empty-state">Produk tidak ditemukan. Coba kata kunci lain atau chat admin via WhatsApp.</div>';return}g.innerHTML=state.filtered.map(card).join('');g.querySelectorAll('[data-select]').forEach(b=>b.addEventListener('click',()=>toggle(b.dataset.select)));g.querySelectorAll('[data-order]').forEach(a=>a.addEventListener('click',()=>{let p=find(a.dataset.order),qty=clean($(`#qty-${p.id}`)?.value);a.href=waUrl(prodMsg(p,qty));a.target='_blank';a.rel='noopener'}))}
function card(p){let sel=state.selected.has(p.id);return`<article class="product-card"><div class="product-top"><span class="product-category">${esc(p.kategori)}</span></div><h3 class="product-name">${esc(p.nama)}</h3><p class="product-desc">${esc(p.deskripsi)}</p><div class="product-meta"><span>${esc(p.ukuran)}</span><span>${esc(p.status)}</span></div><div class="product-price"><strong>${esc(p.harga)}</strong><small>Harga dapat berubah</small></div><div class="qty-wrap"><label for="qty-${esc(p.id)}">Jumlah / kebutuhan</label><input class="qty-input" id="qty-${esc(p.id)}" type="text" placeholder="Contoh: 2 pcs, 1 dus, 5 liter"></div><div class="product-actions"><button type="button" data-select="${esc(p.id)}" class="${sel?'is-selected':''}">${sel?'Terpilih':'Pilih'}</button><a href="#" data-order="${esc(p.id)}">Order</a></div></article>`}
function toggle(id){let p=find(id),qty=clean($(`#qty-${p.id}`)?.value);state.selected.has(id)?state.selected.delete(id):state.selected.set(id,{...p,qty});setStatus(`${state.selected.size} produk dipilih. Klik “Kirim Pilihan” untuk order via WhatsApp.`);renderCatalog()}
function find(id){return state.products.find(p=>p.id==id)||state.filtered[0]}function setStatus(m){let s=$('#catalogStatus');if(s)s.textContent=m}function esc(v){return String(v||'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}
